### ISSUE TITLE
frontmatter error

### ISSUE THREAD

**Issue by apenngrace** [cheat/cheat#708] opened 2022-11-06 21:06 UTC
Thanks for submitting a bug report. Please provide the following information:

```
» cheat -l -t personal
failed to list cheatsheets: failed to load cheatsheets: failed to load sheet: ip, path: /Users/andrew/.config/cheat/cheatsheets/community/ip, err: failed to parse front-matter: failed to unmarshal frontmatter: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `tags [ ...` into sheet.frontmatter
```

**cheat version info**
4.4.0

**cheat configuration info**
If your bug pertains to how cheatsheets are loaded and/or displayed, please
paste here the following information:

1.
```
community: /Users/andrew/.config/cheat/cheatsheets/community
personal:  /Users/andrew/Dropbox/computer_stuff/unix_files/personal_cheat_sheets
cwd:       /Users/andrew/.cheat
```
2. The contents of your `conf.yml` file
---
```
# The editor to use with 'cheat -e <sheet>'. Defaults to $EDITOR or $VISUAL.
editor: vim

# Should 'cheat' always colorize output?
colorize: true

# Which 'chroma' colorscheme should be applied to the output?
# Options are available here:
#   https://github.com/alecthomas/chroma/tree/master/styles
style: monokai

# Which 'chroma' "formatter" should be applied?
# One of: "terminal", "terminal256", "terminal16m"
formatter: terminal16m

# Through which pager should output be piped? (Unset this key for no pager.)
pager: less -FRX

# The paths at which cheatsheets are available. Tags associated with a cheatpath
# are automatically attached to all cheatsheets residing on that path.
#
# Whenever cheatsheets share the same title (like 'tar'), the most local
# cheatsheets (those which come later in this file) take precedent over the
# less local sheets. This allows you to create your own "overides" for
# "upstream" cheatsheets.
#
# But what if you want to view the "upstream" cheatsheets instead of your own?
# Cheatsheets may be filtered via 'cheat -t <tag>' in combination with other
# commands. So, if you want to view the 'tar' cheatsheet that is tagged as
# 'community' rather than your own, you can use: cheat tar -t community
cheatpaths:

  # Paths that come earlier are considered to be the most "global", and will
  # thus be overridden by more local cheatsheets. That being the case, you
  # should probably list community cheatsheets first.
  #
  # Note that the paths and tags listed below are placeholders. You may freely
  # change them to suit your needs.
  #
  # Community cheatsheets must be installed separately, though you may have
  # downloaded them automatically when installing 'cheat'. If not, you may
  # download them here:
  #
  # https://github.com/cheat/cheatsheets
  #
  # Once downloaded, ensure that 'path' below points to the location at which
  # you downloaded the community cheatsheets.
  - name: community
    path: /Users/andrew/.config/cheat/cheatsheets/community
    tags: [ community ]
    readonly: true

  # If you have personalized cheatsheets, list them last. They will take
  # precedence over the more global cheatsheets.
  - name: personal
    path: /Users/andrew/.config/cheat/cheatsheets/personal
    tags: [ personal ]
    readonly: false

  # While it requires no configuration here, it's also worth noting that
  # 'cheat' will automatically append directories named '.cheat' within the
  # current working directory to the 'cheatpath'. This can be very useful if
  # you'd like to closely associate cheatsheets with, for example, a directory
  # containing source code.
  #
  # Such "directory-scoped" cheatsheets will be treated as the most "local"
  # cheatsheets, and will override less "local" cheatsheets. Likewise,
  # directory-scoped cheatsheets will always be editable ('readonly: false').%
```

**Comment by steveshi** [comment] 2022-11-07 19:50
> 

+1

**Comment by Dracos5732** [comment] 2022-11-08 18:19
+1

**Comment by tartofour** [comment] 2022-11-10 08:58
+1

**Comment by apenngrace** [comment] 2022-11-10 18:47
It looks some somebody already submitted [this pull request](https://github.com/cheat/cheat/pull/701) to fix this back in September.

**Comment by PuntoDiGoccia** [comment] 2022-11-11 07:23
> It looks some somebody already submitted [this pull request](https://github.com/cheat/cheat/pull/701) to fix this back in September.

Thanks, did'n notice that - solved the issue for me
Error message quite cryptic tough

**Comment by apenngrace** [comment] 2022-11-11 15:18
I'm kind of hoping that the PR gets merged in, and then somebody update homebrew.  I installed this using `brew`, and I still haven't figured out how to roll back to a previous version.

**Comment by Dracos5732** [comment] 2022-11-11 23:37
@apenngrace I'm in the same boat. I updated my homebrew and it is giving me the error above. Would be nice to have this merged sooner than later.

**Comment by chrisallenlane** [comment] 2022-11-12 15:00
Maintainer here. Just seeing this.

I'm on the road today, but will try to get a fix out tomorrow. Sorry for the headache.

**Comment by chrisallenlane** [comment] 2022-11-15 00:18
For context for others arriving here. Presume an error message that looks like this:

```
failed to list cheatsheets: failed to load cheatsheets: failed to load sheet: foo, path: /home/chris/.dotfiles/cheat/personal/foo, err: failed to parse front-matter: failed to delimit frontmatter
```

What this means is that your cheatsheet's "front-matter" - the metadata associated with a cheatsheet deliminted by `---` - is malformed somehow. Fixing that will resolve the problem.

At some point in the past, malformed cheatsheets were committed to the community cheatsheets, though a community member opened a PR a while ago to resolve that.

In any case, if you encounter such an error message, do the following:
1. Update the community cheatsheets
2. Fix the frontmatter in the offending cheatsheet. (Just look at a known-good cheatsheet as a reference, or delete the frontmatter altogether. The cheatsheet will be valid without it.)

**Comment by chrisallenlane** [comment] 2022-11-15 00:24
To add more context: this isn't, strictly speaking, a bug in `cheat`. Rather, `cheat` is aborting when it encounters malformed data, which was the intended behavior.

With that said, perhaps that intended behavior was stupid :thinking: 

I'm trying to sort out the best way to handle this. I don't want to suppress or bury the error message, but I see how it's arguably a poor design decision that `cheat foo` fails when the (irrelevant) `bar` cheatsheet is malformed.

**Comment by apenngrace** [comment] 2022-11-15 01:15
I was not getting this error in 4.3.3.

**Comment by chrisallenlane** [comment] 2022-11-15 02:18
@apenngrace, so the issue is that `4.4.0` upgraded to a new YAML parser. The new one explicitly throws errors where the old one would silently ignore them.

The root cause of the problem - the corrupted cheatsheets - would have been there for some time. In `4.3.3`, you likely wouldn't have noticed the problem _unless you tried to use the affected sheets_, but the bad data was still there.

As best as I can tell, `4.4.0` did not introduce any regressions - it just surfaced errors that we had in the data.

I've been staring at this for a little while this evening, and I can't think of any good way to disable this behavior. Any attempt to do so would just cause other, subtler problems.

@andrewjkerr, would you mind pasting the first few lines of this cheatsheet into this thread, please?

```
/Users/andrew/.config/cheat/cheatsheets/community/ip
```

Obviously, feel free to redact out anything that you'd like. For our purposes here, we're only interested in the code between the lines demarcated with `---`.

I'm pretty sure I know exactly what your problem is - look at this previous user-submitted PR:

https://github.com/cheat/cheatsheets/pull/73/files

These are the cheatsheets that I mentioned previously, which contained invalid frontmatter, and were corrected by this PR. You'll notice that `ip` is among them.

If your community cheatsheets are configured as read-only, you should be able to simply update them with a `git pull` to resolve this problem. (I'd like to make this possible via `cheat` directly, but I haven't had the time yet.)

Please try updating those community cheatsheets and check if that resolves the problem. I'm happy to help however I can.

**Comment by apenngrace** [comment] 2022-11-15 04:33
I didn't realize until now that I needed to periodically do a `git pull` on the community sheets.  Anyways, if that was only issue, I'd suggest handling this by just catching the error and then maybe outputting an explanation (because the yaml parser error is cryptic).

I'm respectfully suggesting that this error should not be "intended behavior" as is.  Right now it seems like a bug.  It would seem more intended if instead of a parse error, there was a friendlier explanation.  

Also, I just did the `git pull` and it still does not fix it.  This error is a show stopper, because it errors out on some random sheet even though the command I'm giving has nothing to do with it.  Is the yaml parser checking all the sheets all the time?  It would make more sense to me if the sheet that I'm trying to look at has the error and then the program throws the error because of that.  It is less understandable when I'm just doing a `cheat -l` and I get the error just doing that.

As a user, I am not familiar with yaml to troubleshoot the community sheets.  I don't work with that library, so... it's kind of daunting to try to troubleshoot that.

As a user, the behavior in 4.3.3 was preferable to seeing an error like this.  If a goal is to have a validity check on community sheets, maybe that could be handled on another way?  Maybe another sort of validity check command?  Or checked when people merge in new sheets on github?

Does [that PR](https://github.com/cheat/cheat/pull/701) effectively fix the issue?

**Comment by apenngrace** [comment] 2022-11-15 04:35
A snippet showing the error persists, even when a colon is present:

```
cheatsheets/community (master) » cheat -l
failed to list cheatsheets: failed to load cheatsheets: failed to load sheet: ssh, path: /Users/andrew/Dropbox/computer_stuff/unix_files/personal_cheat_sheets/ssh, err: failed to parse front-matter: failed to unmarshal frontmatter: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `tags [ ...` into sheet.frontmatter
cheatsheets/community (master) » cat ssh                  1 ↵
---
tags: [ ssh ]
---
```

**Comment by chrisallenlane** [comment] 2022-11-15 12:15
> I didn't realize until now that I needed to periodically do a git pull on the community sheets.

You do, for now. I recognize that this is a poor user-experience. I have a personal fork of `cheat` on my local machine that implements a `cheat --update` command that does this automatically, but I haven't had time to finish that work yet.

> Anyways, if that was only issue, I'd suggest handling this by just catching the error and then maybe outputting an explanation (because the yaml parser error is cryptic).

The only problem with this approach is that some cheatsheets would likely be "invisible" to `cheat` if they were parsed incorrectly. (`cheat` loads all sheets on most commands so it can build up a database of tags and other things.)

I guess I could just print a warning to stderr and give up on an individual sheet if it contains a formatting error. That feels sloppy, but perhaps it's better than the current behavior.

> It would seem more intended if instead of a parse error, there was a friendlier explanation.

That's fair. The error message is (IMO) appropriate if you're developing `cheat`, but it is poor if you're a user. I'll revise it, since this error will be presented to users.

> Also, I just did the git pull and it still does not fix it.

Good news, though: if you look at the error message, it looks like your personal `ssh` cheatsheet is now the culprit. That likely means that the `git pull` fixed your community cheatsheets, and now only issues remain in your personal sheets.

(`cheat` does a copy-on-write of community cheatsheets when you make personal edits, so what likely happened here is that the defective community `ssh` cheatsheet was copied into your personal directory at some point.)

> If a goal is to have a validity check on community sheets, maybe that could be handled on another way?

Time-permitting, I would like to build some tooling to check sheet validity when users open a pull-request. This is the best solution to this problem - to simply prevent mistakes from being committed in the first place. I haven't had time to get to this yet, unfortunately.

> Does https://github.com/cheat/cheat/pull/701 effectively fix the issue?

I don't believe so. That is functionally equivalent to the change that I made, which introduced the greater strictness that caused this problem.

The author made a complimentary commit against the `cheatsheets` PR which corrected the numerous cheatsheet errors that I mentioned previously. With both PRs merged, those work wonderfully.

However, if you make the YAML parser change to `cheat` but still have some malformed cheatsheets on your machine, you'll have the errors that we're encountering here.

> A snippet showing the error persists, even when a colon is present:

If I'm reading the output correctly, it looks like the error is now in your personal `ssh` cheatsheet, though you `cat`-ed out the community cheatsheet. With luck, perhaps you'll only need to make a few changes to your personal cheatsheets, and you'll be back online.

In any case, thanks for working through this with me. I'll take another look at this tonight when I'm back from the day job, and will try to make the error-handling less user-hostile.

**Comment by chrisallenlane** [comment] 2022-11-15 12:16
As an aside, all of this does make me wonder if we need a `cheat --validate` command to iterate over and validate every cheatsheet on a user's system :thinking:

**Comment by chrisallenlane** [comment] 2022-11-15 22:35
Excellent! Glad to hear you're back online :+1: 

I'll still see what I can do to make all of this a little less user-hostile. Presumably many others are having this problem as well.

**Closed** 2022-12-27 18:03 UTC
Labels: bug
