### ISSUE TITLE
Difference between normal search and regex search

### ISSUE THREAD

**Issue by exploide** [cheat/cheat#495] opened 2019-11-05 15:01 UTC
**A description of the problem**

I noticed that `cheat -s '(?:[0-9]{1,3}\.){3}[0-9]{1,3}'` and `cheat -r -s '(?:[0-9]{1,3}\.){3}[0-9]{1,3}'` return the same output. Both commands find IP addresses, so it seems a regular expression search is performed regardless of the `-r` switch.

I would like to ask if this is intentional?!

That saying, I'm not against always performing regular expression searches. Maybe it does not harm. But then the `-r` switch appears to be useless and could be removed.

**cheat version info**

3.0.3

**Comment by chrisallenlane** [comment] 2019-11-06 01:24
@exploide, this is working as intended, but the specific search you ran is going to produce identical results regardless of whether or not `--regex` was passed.

Under the hood, regexes are indeed used regardless of whether or not `--regex` is specified:

https://github.com/cheat/cheat/blob/197ff58796a92a26dcb80afd961f1cec0a01d23d/internal/sheet/search.go#L12

However, the regexes are assembled differently depending on the presence of the `--regex` flag:

https://github.com/cheat/cheat/blob/197ff58796a92a26dcb80afd961f1cec0a01d23d/cmd/cheat/cmd_search.go#L47-L53

If `--regex` is not passed, it is assumed that we want to perform a case-insensitive search for a literal string. If `--regex` *is* passed, the provided regex is passed directly to the underlying search function without modification.

For a simple example, compare the outputs of the following:

```sh
cheat -s ssh          # this will return case-insenstive matches
cheat --regex -s ssh  # this will return case-sensitive matches
```

So the difference is subtle (and inapplicable to your specific search), but this is working as intended.

Does that make sense?

I'm going to close this ticket, but feel free to re-open it if you believe there's more to be discussed.

Thanks.

**Closed by chrisallenlane** 2019-11-06 01:24 UTC
Labels: bug

**Comment by exploide** [comment] 2019-11-06 09:31
Ok, fine then :)

I think it's not the most intuitive behaviour for a search function but it doesn't bother me. Just wanted to make sure it's not a bug.
