### ISSUE TITLE
Make cheat more 'downstream friendly'

### ISSUE THREAD

**Issue by TomasKorbar** [cheat/cheat#517] opened 2019-12-02 13:55 UTC
Hi @chrisallenlane 
**Is your feature request related to a problem? Please describe.**
I finally got to create an rpm package and i found out that there is no straightforward way how to package cheatsheets. I can download them from cheatsheets repository but since i need to install them under /usr/share directory, cheat can not access them out of the box. Rpm package does not install files under user directory so i need to set environmental variable CHEAT_CONFIGURATION_PATH to /etc/cheat.yml and there set path to cheatsheets to /usr/share/cheat. All this results in need to restart running bash instances to load environmental variable.

**Describe the solution you'd like**
There are multiple possible solutions. For example cheat could by default look into /usr/share/cheat and tag sheets found there as a distribution cheats. Something similar could work with configuration. Cheat could look into /etc/cheat.yml and take content of that file as default values but if user provides configuration in ~/.config/cheat/conf.yml then this configuration would override the systemwide one.
I think these changes could all fail silently on failure and thus not change current cheats behavior  on any system.

**Describe alternatives you've considered**
As i said i've managed to workaround this by creating script in /etc/profile.d with export of CHEAT_CONFIGURATION_PATH variable.

**Additional context**
This results in discomfort when installing cheats rpm package. Also user would have to change script in profile.d to set configuration path back to his home directory.

I know that attempts to solve this issue previously resulted in issues on other systems but if attempts to access those files will be non-mandatory and fail silently then i think it is safe. Feel free to propose some other solution. I just need a way how to make cheat work out of box without touching users home directory in installation and with cheatsheets located in /usr/share/cheat.
I'm doing this not only because it will provide more comfort to Fedora users but also because it is the right thing to do because of https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

Thanks for any help you can provide.

**Comment by exploide** [comment] 2019-12-02 18:59
See also my comment in https://github.com/cheat/cheat/issues/490#issuecomment-560532374 since these issues arise due to the inclusion of the community cheatsheets.

Default config file is also discussed in #501.

**Comment by chrisallenlane** [comment] 2019-12-02 23:54
@TomasKorbar 

Thanks for opening this issue. I want to do whatever I can to make it easy to package `cheat` downstream.

> Rpm package does not install files under user directory so i need to set environmental variable CHEAT_CONFIGURATION_PATH to /etc/cheat.yml and there set path to cheatsheets to /usr/share/cheat.

There _might_ be a better way to do this as-is without making any changes to `cheat` currently.

This is documented nowhere (other than the source), but cheat will currently look for a "system" config file at `/etc/cheat/conf.yml` on Linux systems:

https://github.com/cheat/cheat/blob/master/internal/config/path.go#L43

If you install your default cheatsheet there, you should be able to avoid having to set the envvar.

Maybe you should install the default cheat configs there, set the `cheatpath` to `/usr/share/cheat`, and tag that cheatpath as `community` (or `distribution`?)

There's one drawback to that approach: currently, cheat only looks for a single location for its config file. It doesn't "merge" system and local configs or anything smart like that. It finds a config file, and then proceeds.

That behavior is slightly unfortunate, because `cheat`'s configs are probably more appropriately stored within a user's home directory. Users who wish to use the community cheatsheets and nothing more won't care where their config file is stored, but "power users" would probably prefer that it remains in their home directories for easier editing.

(Certainly, plenty of other Linux software exhibits this behavior, though, so perhaps I'm overthinking this. A "power user" could solve the problem by copying the default system config into their home directory, and then the problem is solved.)

@exploide made some remarks in #490:

> Personally, it wouldn't package them at all and let users fetch them from GitHub. But I might be a bit opinionated about this. Alternatively, they should at least be contained in a separate package that one needs to install explicitly.

Personally, I really like the idea of packaging the cheatsheets in a separate package. IMO, this gives us two big advantages:

1. It spares users like @exploide from installing community cheatsheets if they are unwanted
2. It provides end-users with an easy way to keep community cheatsheets up-to-date

`cheat` does not (and likely will not) provide any mechanism for automatically updating its cheatsheet repositories. If we package the cheatsheets as a separate package, though, the process for updating them becomes well-trodden and straightforward.

@TomasKorbar, @exploide: thoughts on all of the above?

**Comment by TomasKorbar** [comment] 2019-12-03 09:10
> @TomasKorbar
> 
> Thanks for opening this issue. I want to do whatever I can to make it easy to package `cheat` downstream.
> 
> > Rpm package does not install files under user directory so i need to set environmental variable CHEAT_CONFIGURATION_PATH to /etc/cheat.yml and there set path to cheatsheets to /usr/share/cheat.
> 
> There _might_ be a better way to do this as-is without making any changes to `cheat` currently.
> 
> This is documented nowhere (other than the source), but cheat will currently look for a "system" config file at `/etc/cheat/conf.yml` on Linux systems:
> 
> https://github.com/cheat/cheat/blob/master/internal/config/path.go#L43
> 
> If you install your default cheatsheet there, you should be able to avoid having to set the envvar.
> 
I did not know that. That solves my problem.

> Maybe you should install the default cheat configs there, set the `cheatpath` to `/usr/share/cheat`, and tag that cheatpath as `community` (or `distribution`?)
> 
> There's one drawback to that approach: currently, cheat only looks for a single location for its config file. It doesn't "merge" system and local configs or anything smart like that. It finds a config file, and then proceeds.
> 
> That behavior is slightly unfortunate, because `cheat`'s configs are probably more appropriately stored within a user's home directory. Users who wish to use the community cheatsheets and nothing more won't care where their config file is stored, but "power users" would probably prefer that it remains in their home directories for easier editing.
> 
> (Certainly, plenty of other Linux software exhibits this behavior, though, so perhaps I'm overthinking this. A "power user" could solve the problem by copying the default system config into their home directory, and then the problem is solved.)
> 
> @exploide made some remarks in #490:
> 
> > Personally, it wouldn't package them at all and let users fetch them from GitHub. But I might be a bit opinionated about this. Alternatively, they should at least be contained in a separate package that one needs to install explicitly.
> 
> Personally, I really like the idea of packaging the cheatsheets in a separate package. IMO, this gives us two big advantages:
> 
>     1. It spares users like @exploide from installing community cheatsheets if they are unwanted
> 
>     2. It provides end-users with an easy way to keep community cheatsheets up-to-date
> 
> 
> `cheat` does not (and likely will not) provide any mechanism for automatically updating its cheatsheet repositories. If we package the cheatsheets as a separate package, though, the process for updating them becomes well-trodden and straightforward.
> 
> @TomasKorbar, @exploide: thoughts on all of the above?

Now to @exploide opinion.
I understand your point of view. I made new build of cheat v3 in my copr. Now cheatsheets have their own subpackage and they are marked as weak dependency of cheat. That means you can install cheat without cheatsheets. I did similar thing with fzf script. Now users will be provided with option to install cheat with community cheatsheets + fzf script, while other users will be able to install 'clean' cheat without any other things.
`dnf --setopt=install_weak_deps=False install cheat` or you can install cheat and then uninstall cheat-community-cheatsheets package. 
To spare you some googling:)

> I'm not sure if I should post this in #501, #517 or in this issue here, but I want to note down my idea for a first run experience of cheat sweat_smile :
> 
> ```
> $ cheat
> It appears you have run cheat for the first time.
> I created a config file for you at ~/.config/cheat/conf.yml and a directory to store cheatsheets at ~/.cheat.
> 
> Go ahead and note down all the stuff you frequently fail to remember.
> Run "cheat -e <sheetname>" to create and edit your first cheatsheet.
> 
> If you would like to use a community maintained collection of cheatsheets, you can find one at https://github.com/cheat/cheatsheets.
> ```
> 
> Then, the README of cheat/cheatsheets could better explain how to add this collection to the config file.

@exploide is right about usefulness of such or similar dialog. I would just add that it would be great if this dialog could point user to cheat-community-cheatsheets package instead of github url. Because in my opinion if some piece of software is packaged then it is always better to use package instead of downloaded files. You do not have to care for example about deleting in the future.

As always testing version is ready at https://copr.fedorainfracloud.org/coprs/tkorbar/cheat/
Let me know if you are ok with these changes. Long live the upstream :fist_raised: :smile:

**Comment by pirat89** [comment] 2019-12-03 09:21
> @exploide is right about usefulness of such or similar dialog. I would just add that it would be great if this dialog could point user to cheat-community-cheatsheets package instead of github url. Because in my opinion if some piece of software is packaged then it is always better to use package instead of downloaded files. You do not have to care for example about deleting in the future.

As well, you would have installed older versions of various software that doesn't have to be compatible with upstream cheat. But the downstream rpm probably will be compatible with the installed SW.

**Comment by exploide** [comment] 2019-12-03 17:32
Thanks again!

I like that `cheat-community-cheatsheets` is its own package. I'm not a fan of it being installed automatically because it is weak dependency, but at least it can be worked around now :)

Regarding the autocompletion files, I checked what packages provide files in `/usr/share/bash-completion/completions/` and `/usr/share/fish/vendor_completions.d/`. It seems only very few (including cheat) have a dedicated autocompletion package. Most other tools ship the completion files in the main package. But it's not important. Just wanted to point that out in case my comment on that got lost in the other issue thread :yum: 

Regarding something like an introductory first start message, we might have some contradictions, depending on how it all is solved in the end:

Such a message would probably be displayed when no config file was found. But if cheat installs the community cheatsheets as a dependency by default, and this package contains a config file, the message probably never gets displayed.

> I would just add that it would be great if this dialog could point user to cheat-community-cheatsheets package instead of github url. Because in my opinion if some piece of software is packaged then it is always better to use package instead of downloaded files.

When they are installed by default, the last part of the message is mainly useless. Distribution users would have it anyway if not opted out explicitly and people who get it from GitHub see the reference to the repo in the README. So I think the message is only useful when not installing them by default. It can be omitted otherwise. But I also imagine it would be quite hart and dirty for the cheat tool to know how it is installed and adapt the message accordingly :/

**Comment by chrisallenlane** [comment] 2020-01-29 19:55
Hi, guys

`/etc/cheat/conf.yml` appears to have solved @TomasKorbar's initial problem, and the `3.4.0` release should (hopefully) resolve other issues related to the painful setup process. That being the case, I'm going to close this ticket for now.

If you feel like I missed anything here, or that any of these issues are still unresolved, feel free to re-open this ticket. Thanks.

**Closed by chrisallenlane** 2020-01-29 19:55 UTC
Labels: enhancement
