### ISSUE TITLE
config file issues

### ISSUE THREAD

**Issue by yurivict** [cheat/cheat#501] opened 2019-11-12 21:30 UTC
I've created a FreeBSD port for ```cheat```, and got this feedback:

```
This port is a little strange. It installs a binary that just displays
an error message about needing a config file. Perhaps pkg-message
could say how to generate that file?

Except once you generate the config file as upstream instructs, cheat
still can't find it. I'm not sure where it's actually looking for it.

Once you set the env var to point it to the config file, it just
errors out because there's no actual data files installed. The cheat
data files (https://github.com/cheat/cheatsheets) should probably be
installed along with the cheat binary.
Thanks for submitting a bug report. Please provide the following information:
```

Could you please address these concerns and update the code?

Thanks,
Yuri

**Comment by chrisallenlane** [comment] 2019-11-13 00:51
Hi, @yurivict 

Thanks for your port!

> It installs a binary that just displays an error message about needing a config file. Perhaps pkg-message could say how to generate that file?

I'm not thrilled about this user-experience either. That being the case, I'm not entirely sure how to best solve the situation.

Fundamentally, the "problem" is that the config file must be filled out by the user. There really aren't any sensible defaults that can be assumed, because everyone's cheatpaths and such will differ by design.

Perhaps `cheat` just needs to do a better job of informing the user how to generate a config file, should one not be found?

> Except once you generate the config file as upstream instructs, cheat still can't find it. I'm not sure where it's actually looking for it.

Yeah, that's fair. This isn't really documented anywhere right now. I should probably expose this information to the user somehow.

> Once you set the env var to point it to the config file, it just errors out because there's no actual data files installed. The cheat data files (https://github.com/cheat/cheatsheets) should probably be
installed along with the cheat binary.

This might be best solved on your end. Could your package install the community cheatsheets when it installs the executable? (You're then forced to chose a "default" cheatsheet location, though, which again, is not ideal.)

Another option, I suppose, would simply be to output instructions to the user should cheatsheets not be found.

Prior versions of `cheat` bundled cheatsheets with the executable, and I'm confident now that that's the wrong move. One of the solutions above may be sensible, though.

I'm going to pin this issue to solicit feedback from the userbase for a few days. @yurivict, please share any thoughts you have regarding any of the above.

Thanks.

**Comment by assistcontrol** [comment] 2019-11-13 02:13
Hi @chrisallenlane, I'm the one who raised the message @yurivict is following up on.


> Perhaps `cheat` just needs to do a better job of informing the user how to generate a config file, should one not be found?

This, to me, is the right solution. Initial steps for the user are fine, as long as they're told what they are. Ideal would be `No config file found. You can generate one with "cheat --init > ________"`. Even `No config file found. See https://github.com/cheat/cheat for instructions.` would be a positive step.
 
> This might be best solved on your end. Could your package install the community cheatsheets when it installs the executable? (You're then forced to chose a "default" cheatsheet location, though, which again, is not ideal.)

It's feasible for the FreeBSD port to include a cheatsheet tarball, if there were versioned releases (we support unversioned tarballs but they're far from ideal).

An alternate solution would be to put some instructions in the generated conf file. Put an example path in and an instruction of what to git clone.

Again, users can totally handle these things, but I wouldn't have known where to even start if I didn't have the FreeBSD port source tree on hand. I'd suspect that some number of users have installed cheat in some form, gotten an opaque error message, and uninstalled it.

**Comment by yurivict** [comment] 2019-11-13 02:16
You should generate a default config file if it is missing, and print a message to the user what he is expected to do next. Software should be as easy and intuitive as possible, and shouldn't present users with any puzzling questions or difficult action items.

**Comment by assistcontrol** [comment] 2019-11-13 02:17
Yuri's right, that's a much better approach.

**Comment by exploide** [comment] 2019-11-17 18:20
I second this proposal. Instead of printing "could not locate config file", it would be nice to see something like:

```
It seems you have run cheat for the first time.
I created a config file for you at ~/.config/cheat/conf.yml.
Go ahead, adjust it to your needs and set a cheatpath before continuing using cheat.
```

This would probably prevent issues like #491, #499, #507 and this one.

Additionally, once package maintainers start distributing cheat 3.x, previous users could be confused because of the incompatible config file overhaul. This might lead to further issues reported here.
Maybe it could help to extend the first time message from above with:

```
(If you previously used cheat, please note that cheat v3 is a complete rewrite with a new config file format.)
```

Alternatively to the rather verbose first time message, the automatically created config file could contain working defaults for most users. For example just one cheatpath pointing to `~/.cheat` or something like that. So it just starts working. But I understand that you want to educate users about the possibility to configure multiple cheatpaths. Additionally, this alternative would be especially confusing for migrating cheat v2 users.

Another small thing: The config file generated by `cheat --init` contains example cheatpaths in `~/.dotfiles`. I could imagine that some users not familiar with the concept of dotfile repositories have no idea what this is and could be confused because they think folders need to have this name and hesitate to change that. I felt that was the reason for issue #491.

**Comment by assistcontrol** [comment] 2019-11-17 18:27
Agreed. Making a broken-by-default config file to pressure users into adjusting it manually makes sense from an engineering perspective but not from an end-user perspective.

Generate a config file that works. Put examples of other things you can do in comments.

**Comment by chrisallenlane** [comment] 2019-11-17 23:09
Hi, guys

Thanks for the input here. I'll mull it all over and will implement something along these lines over the week or so, as time permits. I agree that there's significant room for improvement over the current implementation.

I've begun developing this project the proper way, and am now opening and merging pull-requests from a personal fork at `chrisallenlane/cheat` (rather than working on `cheat/cheat` directly). I may link in-progress work to this ticket if I require feedback as I work through this.

**Comment by AlJohri** [comment] 2019-12-31 01:53
Completely agree. I just tried using `cheat` after some time and noticed this "failed to load config" issue. I'm not sure why bundling sheets is the wrong move- can't it just provide a reasonable set of defaults that can be overridden? I expect `brew install cheat` to _just work_. I'm not the type of user that will be custom configuring the tool or setting up their own custom cheatsheets. I just want to know how to use `scp` without opening chrome. Uninstalling for now, but hope to be back soon.

**Comment by chrisallenlane** [comment] 2020-01-29 19:38
Hi, guys

I just made some progress on this issue. Please upgrade to `cheat` `3.4.0`:

https://github.com/cheat/cheat/releases/tag/3.4.0

@yurivict 

> You should generate a default config file if it is missing, and print a message to the user what he is expected to do next. 

This is what I decided to do. If a config file is not found, `cheat` now determines an appropriate path for the file based on the operating system, and then creates a `conf.yml` there. `cheat` then notifies the user that a new config was created, and instructs that it must now be edited.

@exploide 

> Another small thing: The config file generated by cheat --init contains example cheatpaths in ~/.dotfiles. I could imagine that some users not familiar with the concept of dotfile repositories have no idea what this is and could be confused...

Yeah, that's a good observation. Accordingly, I removed all references to the `dotfiles` idiom in the configs with `3.4.0`. I also simplified the example config file somewhat, and added additional instructions regarding how to download "community" cheatsheets.

In any case, please give `3.4.0` a try and let me know what you think. We may be ready to finally close this issue.

**Comment by yochananmarqos** [comment] 2020-01-29 20:27
Nope.

```
failed to create config file: /cheat/conf.yml: failed to create directory: mkdir /cheat: permission denied
```

**Comment by chrisallenlane** [comment] 2020-01-29 21:53
Hi, @yochananmarqos 

Will you elaborate on the failure, please? Are you saying that `cheat` is now _broken entirely_ if a system-wide config file is installed? Or are you saying that, if you temporarily move/delete the system-wide config file, `cheat` fails to create a new one?

Also: it's not immediately obvious to me why `cheat` would attempt to create a config file in `/cheat`. (The per-os paths can be viewed [here][].) Do you perhaps have a `CHEAT_CONFIG_PATH` envvar set that could be interfering with the default behavior?

[here]: https://github.com/cheat/cheat/blob/d4c62007027e0e12b75d4d2099d92ec1278133b4/internal/config/paths.go#L28-L38

**Comment by yochananmarqos** [comment] 2020-01-30 01:22
@chrisallenlane 

Sorry I wasn't more clear. When I received that error, I had installed 3.4.0 with no config file or cheatsheets installed. I'm guessing it's due to the binary being installed in `/usr/bin/`?

**Comment by chrisallenlane** [comment] 2020-01-30 23:55
@yochananmarqos 

Thanks for the information. This is very helpful.

I've investigated the code a bit, and I'm reasonably confident that this is happening due to a mis-handling of the `XDG_CONFIG_HOME` environment variable. (Or rather, a misbehavior when the prior is unset.) I should be able to release a fix for this tomorrow.

**Comment by chrisallenlane** [comment] 2020-01-31 01:19
@yochananmarqos, I was able to get to this sooner than expected. When you have a moment, please try the `3.4.1` release. I _think_ it will solve your problem :crossed_fingers: 

https://github.com/cheat/cheat/releases/tag/3.4.1

**Comment by yochananmarqos** [comment] 2020-01-31 15:37
@chrisallenlane: Yep, that did the trick.

**Comment by chrisallenlane** [comment] 2020-01-31 17:21
@yochananmarqos. Excellent. Thanks!

**Comment by chrisallenlane** [comment] 2020-02-02 20:15
I'm going to consider this issue resolved until somebody tells me otherwise, and will now close this ticket. Feel free to re-open it if necessary. Thanks.

**Closed by chrisallenlane** 2020-02-02 20:15 UTC
Labels: question
