### ISSUE TITLE
Window release version runtime error: index out of range [2] with length 2

### ISSUE THREAD

**Issue by maadeagbo** [cheat/cheat#493] opened 2019-11-04 15:13 UTC
I ran the command : `cheat -l` in my window machine using the amd64 release version and ran into this:

```
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
github.com/tj/front.Unmarshal(0xc00011e000, 0x7ef, 0x9ef, 0x74d780, 0xc0004fc150, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/chris/Source/cheat/cheat/vendor/github.com/tj/front/front.go:21 +0x1d1
github.com/cheat/cheat/internal/sheet.New(0xc0004e2100, 0x1c, 0xc0004e2100, 0x1c, 0xc0004f37e0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /home/chris/Source/cheat/cheat/internal/sheet/sheet.go:44 +0x204
github.com/cheat/cheat/internal/sheets.Load.func1(0xc0004e2100, 0x1c, 0x896940, 0xc0000d4230, 0x0, 0x0, 0x1c, 0x2)
        /home/chris/Source/cheat/cheat/internal/sheets/load.go:57 +0x204
path/filepath.walk(0xc0004e2100, 0x1c, 0x896940, 0xc0000d4230, 0xc0000c1a88, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:358 +0x42c
path/filepath.walk(0xc0004e3b40, 0x12, 0x896940, 0xc0002bea10, 0xc0000c1a88, 0x0, 0xc0000bd9f8)
        /usr/local/go/src/path/filepath/path.go:382 +0x306
path/filepath.Walk(0xc0004e3b40, 0x12, 0xc0000bda88, 0xc00049c998, 0x2f48168)
        /usr/local/go/src/path/filepath/path.go:404 +0x106
github.com/cheat/cheat/internal/sheets.Load(0xc0004e1640, 0x1, 0x1, 0x1, 0xc0004e1640, 0xc0000bdb78, 0x40d4b4, 0x3)
        /home/chris/Source/cheat/cheat/internal/sheets/load.go:28 +0x194
main.cmdList(0xc000236660, 0x1, 0xc00000f438, 0x4, 0xc0004e1640, 0x1, 0x1, 0xc00000fe18, 0x7, 0xc00000fe40, ...)
        /home/chris/Source/cheat/cheat/cmd/cheat/cmd_list.go:19 +0x64
main.main()
        /home/chris/Source/cheat/cheat/cmd/cheat/main.go:91 +0x36f
```
My conf.yaml I've attached as a text file
[conf.txt](https://github.com/cheat/cheat/files/3804614/conf.txt)

**Comment by ipstone** [comment] 2019-11-04 22:11
I report the same issue on mac os x: panic: runtime error: index out of range [2] with length 2

**Comment by chrisallenlane** [comment] 2019-11-05 00:21
Hi, @maadeagbo 

I'll confess that I haven't tested `cheat` on Windows yet, so it's entirely possible you've found a bug here.

Please paste here the output from the following commands:

```sh
cheat -v
```

```sh
cheat -d
```

While we're at it, please tell me which version of Windows you're using as well. I'll try to work up a Windows VM in the next few days so I can debug this.

Thanks.

**Comment by chrisallenlane** [comment] 2019-11-05 00:22
@ipstone , I don't see your ticket. Please open or re-open it if I've closed it in error. `cheat` _shoud_ work properly on OSX. (I use it daily.) Thanks.

**Comment by chrisallenlane** [comment] 2019-11-06 01:32
I didn't mean to close this ticket. Sorry! I'll try to get this fixed soon.

**Comment by maadeagbo** [comment] 2019-11-06 02:19
> I didn't mean to close this ticket. Sorry! I'll try to get this fixed soon.

I thought it was a low priority thing or something. I'll get back on my machine when i have the time and post the output to the 2 commands you asked for

**Comment by maadeagbo** [comment] 2019-11-06 05:29
I re-ran the setup procedure to try and see if I can recreate the "steps to breakage" on my machine and the issue no longer shows up

My conf,yaml : 
```
---
# The editor to use with 'cheat -e <sheet>'. Defaults to $EDITOR or $VISUAL.
editor: nvim

# Should 'cheat' always colorize output?
colorize: true

# Which 'chroma' colorscheme should be applied to the output?
# Options are available here:
#   https://github.com/alecthomas/chroma/tree/master/styles
style: monokai

# Which 'chroma' "formatter" should be applied?
# One of: "terminal", "terminal256", "terminal16m"
formatter: terminal256

# The paths at which cheatsheets are available. Tags associated with a cheatpath
# are automatically attached to all cheatsheets residing on that path.
#
# Whenever cheatsheets share the same title (like 'tar'), the most local
# cheatsheets (those which come later in this file) take precedent over the
# less local sheets. This allows you to create your own "overides" for
# "upstream" cheatsheets.
#
# But what if you want to view the "upstream" cheatsheets instead of your own?
# Cheatsheets may be filtered via 'cheat -f <tag>' in combination with other
# commands. So, if you want to view the 'tar' cheatsheet that is tagged as
# 'community' rather than your own, you can use: cheat tar -f community
cheatpaths:

  # Paths that come earlier are considered to be the most "global", and will
  # thus be overridden by more local cheatsheets. That being the case, you
  # should probably list community cheatsheets first.
  #
  # Note that the paths and tags listed below are just examples. You may freely
  # change them to suit your needs.
  #- name: community
  #  path: ~/.dotfiles/cheat/community
  #  tags: [ community ]
  #  readonly: true

  # Maybe your company or department maintains a repository of cheatsheets as
  # well. It's probably sensible to list those second.
  #- name: work
  #  path: ~/.dotfiles/cheat/work
  #  tags: [ work ]
  #  readonly: false

  # If you have personalized cheatsheets, list them last. They will take
  # precedence over the more global cheatsheets.
  - name: personal
    path: ~\scripts\cheatsheets-master\
    tags: [ personal ]
    readonly: false
```

cheat -l
```
\7z            C:\Users\Moses\scripts\cheatsheets-master\7z            compression,personal
\ab            C:\Users\Moses\scripts\cheatsheets-master\ab            personal
\alias         C:\Users\Moses\scripts\cheatsheets-master\alias         personal
\ansi          C:\Users\Moses\scripts\cheatsheets-master\ansi          personal
\apk           C:\Users\Moses\scripts\cheatsheets-master\apk           packaging,personal
\apparmor      C:\Users\Moses\scripts\cheatsheets-master\apparmor      personal
\apt           C:\Users\Moses\scripts\cheatsheets-master\apt           packaging,personal
\apt-cache     C:\Users\Moses\scripts\cheatsheets-master\apt-cache     packaging,personal
\apt-get       C:\Users\Moses\scripts\cheatsheets-master\apt-get       packaging,personal
\aptitude      C:\Users\Moses\scripts\cheatsheets-master\aptitude      packaging,personal
\aria2c        C:\Users\Moses\scripts\cheatsheets-master\aria2c        personal
\asciiart      C:\Users\Moses\scripts\cheatsheets-master\asciiart      personal
\asterisk      C:\Users\Moses\scripts\cheatsheets-master\asterisk      personal
\at            C:\Users\Moses\scripts\cheatsheets-master\at            personal
\awk           C:\Users\Moses\scripts\cheatsheets-master\awk           personal
\bash          C:\Users\Moses\scripts\cheatsheets-master\bash          personal
...
```

`cheat -v` : `3.0.3`
`cheat -d` : `personal: C:\Users\Moses\scripts\cheatsheets-master`

The only strange thing is that I need to add a `\` when I want to see a cheat ( i.e. `cheat \7z` )

**Comment by chrisallenlane** [comment] 2019-11-06 10:29
> I thought it was a low priority thing or something.

Nah. I just hit "Close and comment" when I meant to hit "Comment". lol.

Thanks for posting this information. This is really helpful.

> The only strange thing is that I need to add a \ when I want to see a cheat ( i.e. cheat \7z )

I re-opened this ticket, because this still isn't working as expected. Example - do you see how each of your cheatsheets (in `cheat -l`) is prefaced with a backslash? That's why you're having to preface cheatsheets with `\` - `cheat` is interpreting that slash as part of the sheet's "title", but that's not intended behavior.

My guess is that this has something to do with Windows using `\` as the directory separator, where the Unixes use `/`. There's probably some elegant way to handle this, and I'm definitely not doing it. (I know PHP has `DIRECTORY_SEPARATOR` to handle this detail. Maybe Golang has something similar.)

I'll see if I can get that squared away. In the meantime, I'm glad you found a workaround that allows you to use the app.

I'll update this ticket when I have published a fix. Thanks.

**Comment by chrisallenlane** [comment] 2019-11-06 10:30
See: https://stackoverflow.com/questions/9371031/how-do-i-create-crossplatform-file-paths-in-go

**Comment by maadeagbo** [comment] 2019-11-11 16:01
And on another note, I was able to repro what caused the first error message I experienced. I had a `conf.txt` temporary file in the same folder I had my `conf.yaml` file. Even though my config path was explicit to search for a `.yaml` file, it seems that just the presence of a similarly named file w/ a different extension was enough to make it read the wrong file.

It looks like you look explicitly for the yaml file though:
```go
// Windows config paths
	} else if sys == "windows" {

		paths = []string{
			fmt.Sprintf("%s/cheat/conf.yml", os.Getenv("APPDATA")),
			fmt.Sprintf("%s/cheat/conf.yml", os.Getenv("PROGRAMDATA")),
		}
	}
```
so I don't know why this happens 😕

**Comment by chrisallenlane** [comment] 2019-11-12 01:39
> And on another note, I was able to repro what caused the first error message I experienced.

That's pretty weird. I tried to reproduce it on Linux, but could not. (As you said, I'm looking for an exact file path.) Maybe it's a Windows thing?

Speaking of:

I spent a few hours tonight trying to set up a Windows VM for testing, but I'm having a hell of a time of it. (Primarily due to the fact that I'm running _ancient_ hardware and software which seemingly doesn't play nicely with Virtualbox 6, which is required for running Microsoft's testing VMs.) I'll try to get something worked up this week, though. I'd like to get this solved soon, as this is seemingly `cheat`'s last (known) bug.

**Comment by maadeagbo** [comment] 2019-11-13 17:57
> That's pretty weird. I tried to reproduce it on Linux, but could not. (As you said, I'm looking for an exact file path.) Maybe it's a Windows thing?

I guess it maybe because I labeled my file w/ the `.yaml` extension instead of `.yml`. So instead of finding the hardcoded file, it found the first file that matched (in this case being the `.txt` version)

**Closed** 2019-11-20 01:06 UTC
Labels: bug, priority, windows

**Comment by chrisallenlane** [comment] 2019-11-20 01:09
@maadeagbo: @stefanc contributed a patch that should resolve this issue, so I'm closing it. Please upgrade to `3.1.1` and confirm that it now works as expected. If not, feel free to re-open this ticket. Thanks.

**Comment by chrisallenlane** [comment] 2019-11-20 01:16
Oh, @maadeagbo, @stefanc - I have a question for you both:

@maadeagbo, you said that you're using that batch file to execute `cheat`, correct? Do either of you think that a batch file should be included in this project for Windows users? I haven't really used Windows in a meaningful way since 2006 or so, so I have no idea what the app packaging situation looks like.

**Comment by stefanc** [comment] 2019-11-20 08:55
@chrisallenlane I have added `CHEAT_CONFIG_PATH` as an environment variable so I don't need to rely on a batch file.

I plan to take a look at properly generating windows paths in the config file if running on windows, and also looking for the config file in a default location (which should probably be `$env:APPDATA\Cheat\conf.yml` 🤔) when I have time.

**Comment by stefanc** [comment] 2019-11-20 11:32
> and also looking for the config file in a default location

Scratch that. It's already implemented and it works great 👍

**Comment by maadeagbo** [comment] 2019-11-22 19:53
I just don't like setting environment variables on my machine all the time 😄  So I just have a scripts folder where I alias things I want to run from the command prompt
