### ISSUE TITLE
No cheatsheet found for tar

### ISSUE THREAD

**Issue by Tlaloc-Es** [cheat/cheat#461] opened 2019-06-01 20:42 UTC
I installed cheat with

`sudo pip install cheat`

When I execute this:

`cheat tar` 

or anything, I always get 

> No cheatsheet found for tar

**Comment by pirat89** [comment] 2019-06-05 10:19
That's duplicate of https://github.com/cheat/cheat/issues/448. I suggest you to close this one and track the other one.

**Closed** 2019-06-05 20:05 UTC
