### ISSUE TITLE
`cheat -l` gives error if cheatpath dir contains `.gitignore` (but no `.git/`)

### ISSUE THREAD

**Issue by sevens** [cheat/cheat#699] opened 2022-08-27 19:17 UTC
**A description of the problem**

When a cheatpath dir contains a `.gitignore` file (but no `.git/` dir), `cheat -l` shows an error like `failed to list cheatsheets: failed to load cheatsheets: failed to identify .git directory: failed to stat path cheatsheets/.gitignore: stat cheatsheets/.git: no such file or directory`

**cheat version info**
4.3.2 (4.0.0 works fine, didn't test intermediate versions)

**cheat configuration info**
`cheat -d`:
```
test: cheatsheets
```

`conf.yml` file:
See below (using a testing environment to isolate and reproduce the bug).

**Steps to reproduce**
I can reproduce this issue on a small/isolated environment:
* Create a temp dir and `cd` into it
* Create a `conf.yml` file in that dir, containing:
  ```yml
  ---
  cheatpaths:
    - name: test
      path: ./cheatsheets
      tags: [ test ]
      readonly: true
  ```
* Create cheatpath:
  ```sh
  $ mkdir cheatsheets
  ```
* Base check:
  ```sh
  $ CHEAT_CONFIG_PATH=./conf.yml cheat -l
  ```
  This shows an empty listing, no errors
* Create `.gitignore`:
  ```sh
  $ touch cheatsheets/.gitignore
  ```
  and now `cheat -l` is broken:
  ```
  $ CHEAT_CONFIG_PATH=./conf.yml cheat -l
  failed to list cheatsheets: failed to load cheatsheets: failed to identify .git directory: failed to stat path cheatsheets/.gitignore: stat cheatsheets/.git: no such file or directory
  ```
* Creating a `.git/` dir as well fixes it:
  ```sh
  $ mkdir cheatsheets/.git
  $ CHEAT_CONFIG_PATH=./conf.yml cheat -l
  ```
  now shows the empty listing again, no errors. N.b.: removing the `.git/` dir brings back the error again.

After some digging, I guess it's due to truncating the `path` part at https://github.com/cheat/cheat/blob/db3d7e53a45edbaf21c6c8b5b2eaef28d982868d/internal/sheets/gitdir.go#L63-L67 ?

**Comment by chrisallenlane** [comment] 2022-08-27 21:02
Ah, damn. I can confirm this behavior. As you've pointed out, this is surely due to some of the changes implemented on Friday.

Thanks for the very thorough bug report. I'll see if I can scrape together some time to fix this tomorrow.

**Comment by chrisallenlane** [comment] 2022-08-27 21:06
Note to self: it's obvious now that attempting to base this logic off of string parsing is the path to ruin. I need to re-implement all of this using `go-git`.

**Comment by sevens** [comment] 2022-08-27 22:39
> ...
> Edited note to self: the disgusting 30-minute solution is just to modify the offending logic to check for `.gitignore` , `.gitkeep`, and `.gitattributes` files, I guess. That will buy some time to work out a more proper solution.

FYI: might want to add `.gitmodules` as well ;)  (from [git submodules](https://www.git-scm.com/docs/gitsubmodules))

**Comment by chrisallenlane** [comment] 2022-08-28 02:14
@sevens, please try the `4.3.3` release, which was published moments ago:
https://github.com/cheat/cheat/releases/tag/4.3.3

I believe this should solve the problem.

I'm going to optimistically close this ticket as resolved, but feel free to re-open if necessary.

Thanks!

**Closed by chrisallenlane** 2022-08-28 02:14 UTC
Labels: bug, priority

**Comment by sevens** [comment] 2022-08-28 16:01
Thanks for the quick fix!  I've tested it on 2 machines and the fix works for me.

FWIW: I just realized that `.git` can also be a plain file in case of a worktree checkout, just to keep things simple I gues...  I just did a quick test with this, using the community cheatsheets repository, and this doesn't give an error.  However, `.git` (and `.github/*`) do appear in the `cheat -l` output, no idea if either of them did before 4.3.3.  Output:

```sh
$ CHEAT_CONFIG_PATH=./conf.yml cheat -l | head -5
title:                    file:                                    tags:
.git                      cheatsheets-wt/.git                      test
.github/LICENSE.txt       cheatsheets-wt/.github/LICENSE.txt       test
.github/README.md         cheatsheets-wt/.github/README.md         test
7z                        cheatsheets-wt/7z                        compression,test
```

**Comment by chrisallenlane** [comment] 2022-08-29 10:12
@sevens, thanks for following up.

Ah, geez. That's annoying. This has been shockingly hard to get right. There's a huge amount of nuance to all of this that I didn't anticipate.

At least we aren't crashing anymore, though.

With the last release, I made an invisible but important change: when the installer runs, `git` operations (the cloning) are now performed by `go-git`, rather than a shell call to `git` on the `PATH`.

Now that `go-git` is in the project, I can refactor all of this problematic code to determine where we are using `git` operations rather than string parsing, because the string parsing approach seems fraught with peril.

Time permitting, I'll take a crack at that next weekend. In the meantime, at least we aren't crashing.

Thanks for the help :slightly_smiling_face:

**Comment by sevens** [comment] 2022-08-29 16:07
Yeah, using a library is probably much safer (and future-proof, e.g. the whole worktree stuff is fairly new AFAIK, and still somewhat experimental).  Good luck with refactoring.

You're welcome, and thanks for making `cheat` in the first place; I find it very useful and use it daily!
