### ISSUE TITLE
yaml unmarshal error :: Cannot unmarshal !!str tags [ ... into sheet.frontmatter

### ISSUE THREAD

**Issue by Almenon** [cheat/cheat#736] opened 2023-09-02 03:44 UTC
Same problem as https://github.com/cheat/cheat/issues/728 is still occurring with latest release on WSL (ubuntu). 

reproduction steps:
1. Install by running first code block in https://github.com/cheat/cheat/blob/master/INSTALLING.md
2. run a command like `cheat -l` or `cheat nmap`

Workaround: running `cheat -d` after installing, before running any other commands.

**Comment by chrisallenlane** [comment] 2023-12-13 19:32
@Almenon, thanks for the bug report, and sorry for my delay getting back to you.

I can reproduce this behavior, but I consider this to be a feature and not a bug, and I don't plan to change the current behavior. I'll explain my reasoning.

As you've discovered, this error occurs when `cheat` attempts to load a cheatsheet that contains malformed front-matter. There are essentially only four behaviors that we could implement here:

1. Fail with an explicit error message. (This is the current behavior.)
2. Entirely ignore the cheatsheet with the malformed front-matter
3. Discard the malformed front-matter, but otherwise attempt to use the cheatsheet.
4. Discord the malformed front-matter, write a warning to `stderr`, and attempt to use the cheatsheet.

Of the four, I think option one - the current behavior - is preferable.

If we pursue option two, we'll inevitably "hide" cheatsheets from users as they become malformed through editing. Worse, we'll also hide the fact that we're hiding them! The user will simply be unaware that their cheatsheets contain errors, and that they're being silently ignored.

If we pursue option three, cheatsheet content will still be searchable (via `-s`), but tagging will be silently broken. And, once again, the user will be unaware that there's a problem.

Option four perhaps improves upon option three, but there's still a risk that the user simply does not see the error written to `stderr`. This risk increases with the length of a cheatsheet, and some cheatsheets can be quite long.

With all of that said, I think the "hard" failure is probably best for the user in the long-term, if inconvenient in the short-term (in that a user will be required to fix their cheatsheets immediately, prior to resuming their use of `cheat`).

I'm going to close this ticket, but I'm open to feedback if you have a differing opinion, and/or other suggestions for behaviors that I have not considered above.

Thanks.

**Closed by chrisallenlane** 2023-12-13 19:32 UTC
Labels: bug
